apiVersion: kommander.mesosphere.io/v1beta1
kind: KonvoyCluster
metadata:
  name: STUDENT000
  labels:
    cluster: prod
spec:
  cluster:
    addons:
    - addonsList:
      - enabled: true
        name: kibana
      - enabled: true
        name: reloader
      - enabled: true
        name: velero
      - enabled: true
        name: dashboard
      - enabled: true
        name: dex-k8s-authenticator
      - enabled: true
        name: elasticsearch
      - enabled: true
        name: traefik
      - enabled: true
        name: defaultstorageclass-protection
      - enabled: true
        name: fluentbit
      - enabled: true
        name: opsportal
      - enabled: true
        name: elasticsearchexporter
      - enabled: false
        name: gatekeeper
      - enabled: false
        name: localvolumeprovisioner
        values: |
          # Multiple storage classes can be defined here. This allows to, e.g.,
          # distinguish between different disk types.
          # For each entry a storage class '$name' and
          # a host folder '/mnt/$dirName' will be created. Volumes mounted to this
          # folder are made available in the storage class.
          storageclasses:
            - name: localvolumeprovisioner
              dirName: disks
              isDefault: false
              reclaimPolicy: Delete
              volumeBindingMode: WaitForFirstConsumer
      - enabled: true
        name: prometheus
      - enabled: true
        name: external-dns
        values: |
          aws:
            region:
          domainFilters: []
      - enabled: false
        name: flagger
      - enabled: false
        name: istio
      - enabled: false
        name: kudo
      - enabled: true
        name: prometheusadapter
      - enabled: true
        name: traefik-forward-auth
      - enabled: true
        name: cert-manager
      - enabled: false
        name: awsebsprovisioner
        values: |
          storageclass:
            isDefault: false
      - enabled: true
        name: dex
      - enabled: true
        name: konvoyconfig
      - enabled: false
        name: nvidia
      - enabled: true
        name: awsebscsiprovisioner
      - enabled: true
        name: kube-oidc-proxy
      configRepository: https://github.com/mesosphere/kubernetes-base-addons
      configVersion: stable-1.17-2.0.2
    - configRepository: https://github.com/mesosphere/kubeaddons-dispatch
      configVersion: stable-1.17-1.2.2
      addonsList:
      - name: dispatch
        enabled: false
    - configRepository: https://github.com/mesosphere/kubeaddons-kommander
      configVersion: stable-1.17-1.1.0
      addonsList:
      - name: kommander
        enabled: false
    containerNetworking:
      calico:
        encapsulation: ipip
        version: v3.13.4
    containerRuntime:
      containerd:
        version: 1.3.4
    kubernetes:
      admissionPlugins:
        enabled:
        - NodeRestriction
        - AlwaysPullImages
      cloudProvider:
        provider: aws
      networking:
        podSubnet: 192.168.0.0/16
        serviceSubnet: 10.0.0.0/18
      version: 1.17.8
    nodePools:
    - name: worker
    version: v1.5.0
  provisioner:
    provider: aws
    version: v1.5.0
  cloudProviderAccountRef:
    name: aws-credentials