apiVersion: workspaces.kommander.mesosphere.io/v1alpha1
kind: ProjectRole
metadata:
  name: projectadminrole
  namespace: project
spec:
  rules:
    - apiGroups: [""] # "" indicates the core API group
      resources: ["*"]
      verbs: ["*"]
